apiVersion: batch/v1
kind: Job
metadata:
  name: notifier
spec:
  template:
    spec:
      containers:
      - name: barograph-notifier
        image: maysams/barograph-notifier
        volumeMounts:
        - name: cluster-conf
          mountPath: "/app/env"
          readOnly: true
        env:
          - name: BAR_CONFIG
            value: /app/env/environment.conf
      volumes:
      - name: cluster-conf
        secret:
          secretName: cluster-conf
      restartPolicy: Never
